import "./globals.css";
import Header from "./components/Header";



export const metadata = {
    title: "Publishing",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <header>
                    <Header />
                </header>

                {children}
                <footer>
                    footer
                </footer>
            </body>
        </html>
    );
}
